import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarClientWrapper from "@/components/ui/SidebarClientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <div className="hidden md:block">
            {/* Sidebar solo visible en desktop, puedes adaptar para móvil con Sheet si lo deseas */}
            <SidebarClientWrapper />
          </div>
          {/* Contenido principal */}
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
